### ISSUE TITLE
Ruby attribute references

### ISSUE THREAD

**Issue by zfy0701** [yinwang0/rubysonar#10]
For code as follow

```
class A
  @f = 0
  def self.f
    @f
  end
end

a = A.new
a.f
```

it will create a definition for the instance variable f (qname: A::f), and one for the class method (qname: A.f)
however, the reference generated is strange:
f in line 4 referenced to A.f
a.f in last line referenced to A::f

it looks like we want the contrary result

it looks like the reason is: f in line 4 is a Name node, which should really be a attribute node.

and a.f in last line is attribute node, which should be a method call I believe.

**Comment by chenyukang** [comment]
```ruby
a.f
```
of course will trigger a runtime error: 
`<main>': undefined method `f' for #<A:0x007fb21c153620> (NoMethodError)

since it is not a instance method, 

```ruby 
class A
  attr_accessor :f

  def self.fth
    puts "in methods"
    @f = 1
  end
end

a = A.new
a.f = 1
puts a.f
```
actually this will analyzed right.
